version: v1.0.3.{build}
pull_requests:
  do_not_increment_build_number: true
os: Visual Studio 2015
configuration: Release
nuget:
  account_feed: true
  project_feed: true
before_build:
- cmd: >-
    dnvm upgrade

    dnu restore

    cd cmd

    npm install

    node aspnet5-version.js

    cd ..
build:
  publish_nuget: true
  verbosity: minimal
artifacts:
- path: artifacts\bin\AutomaticSharp\**\*.nupkg
  name: NuGet Packages
deploy:
- provider: NuGet
  api_key:
    secure: vclZPRGQBqWGDezZ6hXnmNRiILR+c7I2hqysI5leFRyCc89gd3W7ezyc9rWQ4VyO
  symbol_server: 
  artifact: 
  on:
    branch: master
    appveyor_repo_tag: true