version: 1.0.5-CI{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2015
configuration: Release
nuget:
  account_feed: true
  project_feed: true
build_script:
- cmd: >-
    dotnet restore src\AutomaticSharp

    dotnet restore src\AutomaticSharp.Auth

    cd cmd

    npm install

    node aspnet5-version.js

    cd ..

    dotnet pack src\AutomaticSharp --configuration Release --output "artifacts\bin\AutomaticSharp"

    dotnet pack src\AutomaticSharp.Auth --configuration Release --output "artifacts\bin\AutomaticSharp"
artifacts:
- path: artifacts\bin\AutomaticSharp\**\*.nupkg
  name: NuGet Packages
deploy:
- provider: NuGet
  api_key:
    secure: vclZPRGQBqWGDezZ6hXnmNRiILR+c7I2hqysI5leFRyCc89gd3W7ezyc9rWQ4VyO
  on:
    branch: master
    appveyor_repo_tag: true